### ISSUE TITLE
travis builds failing due to 'Cannot find module js/lib/urlUtil'

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#12276]
my fault because i forgot mac is not case-sensitive but linux is.

caused by 4e7995dd468f7e6987a0ceca3938e9d0bc6fdfbe
