### ISSUE TITLE
ledger client boot error:  { Error: Cannot find module 'brave-crypto'

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11799]
### Description

ledger client boot error:  { Error: Cannot find module 'brave-crypto'

### Steps to Reproduce

  1. Clear the profile data
  2. Run the browser
  2. Open about:preferences#payments
  3. Switch on

**Actual result:**

````
ledger client boot error:  { Error: Cannot find module 'brave-crypto'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/lib/brave-beta/resources/electron.asar/common/reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/lib/brave-beta/resources/app.asar/node_modules/bat-client/index.js:7:21
    at Object.<anonymous> (/usr/lib/brave-beta/resources/app.asar/node_modules/bat-client/index.js:1431:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
````

**Expected result:**

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

I'm not sure.

**Comment by luixxiul** [comment]
@srirambv confirmed it was reproducible on 0.19.x.

**Comment by bsclifton** [comment]
Was caused by https://github.com/brave/browser-laptop/commit/e7165b52dd6aa1e5c03f2e082283b271e96e5344#diff-eb1f8c8a44791e608fb0fbe96819221eR59 when fixing https://github.com/brave/browser-laptop/issues/11929

We'll need to fix this also for 0.20.x+ (cc: @darkdh).  For 0.19.x, I backed out the `Brave/brave` wildcards for ignore (put in place so that other channels don't get packaged also) and am confirming this fix now.

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/41dc7cfd822b5b12f95328f2dac863458ac25124
