### ISSUE TITLE
about:welcome shown on each launch

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10425]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
about:welcome shown on each launch

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.18.22
-- | --
rev | d850e28
Muon | 4.3.9

- Steps to reproduce:
    1. Clean install the preview build
    2. Close the about:welcome tab and open a page in the new tab
    3. Close/Quit browser and restart, about:welcome is shown again
    
- Actual result:
about:welcome shown on each launch

- Expected result:
Should be shown only on the first launch after install, subsequent launches should not show irrespective of whether user visits any site or just open and close the browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Found in 0.18.21 packaged build

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by cezaraugusto** [comment]
@srirambv I left a comment in DM for you. Tried in 0.18.22 in a clean-state machine (first time Brave download), and couldn't repro. Welcome page should not show up again once you close it.

Let me know here or over Slack if you have other steps, I'm going to close this but please re-open as needed.

**Comment by srirambv** [comment]
This seems like an issue with session not getting saved after closing the browser as mentioned in https://github.com/brave/browser-laptop/issues/10423.

**Comment by srirambv** [comment]
@cezaraugusto  Still seeing on 0.18.22

![about_welcome](https://user-images.githubusercontent.com/17010094/29269429-4b8553a6-80e9-11e7-8d86-6df8b4c0cd59.gif)

**Comment by cezaraugusto** [comment]
this seems related to session state not being saved in time. @bsclifton any take on this?

**Comment by luixxiul** [comment]
FWIW I get this error on Debian when closing the browser:

````
Error saving app state:  TypeError: immutableWndPayload.get is not a function
    at immutablePayload.get.forEach (/usr/lib/brave/resources/app.asar/app/sessionStore.js:83:44)
    at List.__iterate (/usr/lib/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at List.forEach (/usr/lib/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:4383:19)
    at Promise (/usr/lib/brave/resources/app.asar/app/sessionStore.js:82:46)
    at Promise (<anonymous>)
    at Object.module.exports.saveAppState (/usr/lib/brave/resources/app.asar/app/sessionStore.js:76:10)
    at saveAppState (/usr/lib/brave/resources/app.asar/app/sessionStoreShutdown.js:88:23)
    at sessionStoreQueue.push (/usr/lib/brave/resources/app.asar/app/sessionStoreShutdown.js:140:7)
    at async.queue (/usr/lib/brave/resources/app.asar/app/sessionStoreShutdown.js:54:5)
    at /usr/lib/brave/resources/app.asar/node_modules/async/dist/async.js:4069:9
````

**Comment by srirambv** [comment]
I can reproduce this issue on 0.18.22 in 3 out of 5 attempts. #10480  could also be similar to this. Reopening the issue

**Comment by cezaraugusto** [comment]
thanks Sriram

**Comment by bbondy** [comment]
I think it could be related to #10485 that @luixxiul mentioned above. Please re-test this with 0.18.23

**Comment by srirambv** [comment]
Works fine on 0.18.23.
