### ISSUE TITLE
Unable to build on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dan-da** [brave/browser-laptop#228]
This is my first time trying to build.  Following instructions at 
https://github.com/brave/browser-laptop#installation

gyp http GET https://nodejs.org/dist/v0.10.25/SHASUMS256.txt
gyp http 200 https://nodejs.org/dist/v0.10.25/SHASUMS256.txt
make: Entering directory `/home/danda/dev/browser-laptop/node_modules/abp-filter-parser-cpp/node_modules/bloom-filter-cpp/build'
  CXX(target) Release/obj.target/bloom-filter-cpp/addon.o
In file included from ../addon.cpp:7:0:
../BloomFilterWrap.h:30:25: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
   static void New(const v8::FunctionCallbackInfo<v8::Value>& args);

build log attached.

$ lsb_release -a | grep Desc
Description:    Ubuntu 14.04.1 LTS
[build-output.txt](https://github.com/brave/browser-laptop/files/99855/build-output.txt)

**Comment by groksrc** [comment]
This is essential the same problem: https://github.com/brave/browser-laptop/issues/214

**Comment by diracdeltas** [comment]
Yep, closing as duplicate.
