### ISSUE TITLE
v0.9.2 Dev Channel Show no UI and JSON instead

### ISSUE THREAD

**Issue by edouard-lopez** [brave/browser-laptop#1466]
The browser starts but I got no UI except from the content below

### Content
I don't know any of the website 
```
"tinybuddha.com":[{"w": 300, "h": 250, "rid": "div-gpt-ad-1409556045567-1"}, 
{"w": 300, "h": 250, "rid": "div-gpt-ad-1409556045567-2"}, 
{"w": 300, "h": 250, "rid": "div-gpt-ad-1409556045567-3"}, 
{"w": 300, "h": 250, "rid": "div-gpt-ad-1409556045567-4"}], 
"pentapostagma.gr":[{"w": 300, "h": 250, "rid": "AMIfr_48861084_1_25854968_c7df0a"}, 
{"w": 300, "h": 250, "rid": "AMIfr_48861085_1_20176088_79362e"}, 
{"w": 300, "h": 250, "rid": "AMIfr_48861236_1_27150258_05e3c7"}], 
"ads2020.marketing":[{"w": 728, "h": 90, "rid": "aswift_1_expand"}], 
"bitacoras.com":[{"w": 300, "h": 250, "rid": "aswift_0_expand"}], 
"honestjohn.co.uk":[{"w": 300, "h": 250, "rid": "ad_MPU_250_1"}, 
{"w": 728, "h": 90, "rid": "ad_leaderboard_90"}], 
"revolvermaps.com":[{"w": 160, "h": 600, "rid": "aswift_0_expand"}], 
"cnm.com":[{"w": 300, "h": 250, "rid": "placement_184500_0"}], 
"vcpost.com":[{"w": 728, "h": 90, "rid": "adunit_main_center_bottom_computer"}],
"caracol.com.co":[{"w": 300, "h": 250, "rid": "D149730668_89411422748"}, 
{"w": 300, "h": 250, "rid": "I149730668_89411433068"}, 
{"w": 300, "h": 250, "rid": "google_ads_iframe_/7811748/caracol_web_co/portada/mpu3_0__container__"}, 
{"w": 300, "h": 250, "rid": "D153511148_93935807108"}, 
{"w": 728, "h":
```

### Install

```
$ sudo dpkg -i ./brave_0.9.2_amd64.deb
(Reading database ... 304059 files and directories currently installed.)
Preparing to unpack ./brave_0.9.2_amd64.deb ...
Unpacking brave (0.9.2-1) over (0.8.3-1) ...
Setting up brave (0.9.2-1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for mime-support (3.58ubuntu1) ...
```

### Env

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

### `v0.9.1`

Is blank and dark

### Debug

I have access to the menu and find this in the console:

    Uncaught Error: Cannot find module '/usr/share/brave/resources/atom.asar/renderer/init.js'

**Comment by luixxiul** [comment]
Are you still seeing this after upgrading to 0.9.5?

CC: @bbondy

**Comment by luixxiul** [comment]
Closing for now.
