### PR TITLE
Give a hint about the required Node.js version

### LINKED ISSUE #209: Javascript error after build
screen shot 2016-01-20 at 12 59 59 pm

OS X 10.11.1

Performed clone from repo, installed via NPM (no errors, I think), created .app and then built the .dmg - but no dice.

Do I just repeat the install/build process?

`
Uncaught Exception:
Error: Cannot find module '/Applications/Brave.app/Contents/Resources/app/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/Brave.app/Contents/Resources/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)`

### PR DESCRIPTION
**Pull request by elia**
fixes #209

### CODE REVIEW

**Comment by bbondy** [comment]
Thanks, the package.json lists us as 5.0 but I'm not certain that's correct.
Would you mind trying with 5.0 via nvm or n and if that works then update this PR to v5+?

**Comment by elia** [comment]
@bbondy done. Works fine with 5.0.

**Comment by bbondy** [comment]
Thank you for checking @elia, really appreciate it!

**Comment by elia** [comment]
:+1:
