### ISSUE TITLE
Seeing JavaScript errors in developer tools on each page

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#14890]
Reported by @snyderp 

### Description
When opening the developer tools on any page (the content developer tools), you'll notice a lot of JavaScript errors

### Steps to Reproduce

  1. Visit https://brave.com
  2. Open developer tools
  3. View console

**Actual result:**

![screen shot 2018-07-31 at 11 23 10 pm](https://user-images.githubusercontent.com/4733304/43504550-bcc82be4-9518-11e8-834b-1ebceb202235.png)

```
Uncaught ReferenceError: require is not defined
    at adInsertion.js:5
pageInformation.js:159 error resolving rule at position #0
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #1
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #2
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #3
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #4
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #5
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #6
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #7
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #8
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #9
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #10
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #11
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #12
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #13
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #14
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #15
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #16
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #17
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
chrome.ipcRenderer.once @ pageInformation.js:159
pageInformation.js:159 error resolving rule at position #18
 Error: invalid expression
    at resolve (pageInformation.js:119)
    at EventEmitter.chrome.ipcRenderer.once (pageInformation.js:157)
    at Object.onceWrapper (VM66 extensions::event_emitter:292)
    at emitTwo (VM66 extensions::event_emitter:105)
    at EventEmitter.emit (VM66 extensions::event_emitter:193)
    at EventEmitter.ipcRenderer.emit (VM65 extensions::ipc_utils:35)
```

**Expected result:**
no JavaScript errors

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### Additional Information

 
Brave: 0.23.73 
V8: 6.8.275.24 
rev: 50bdb6df42550dd14f5636770ec8585aa26e361b 
Muon: 8.0.3 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.75

**Comment by bsclifton** [comment]
caused by https://github.com/brave/browser-laptop/pull/14851

cc: @riastradh-brave

**Comment by bsclifton** [comment]
Re-opening since the main cause of these issues is with the ledger (`messages.LEDGER_PUBLISHER_RESPONSE` ipc message). Caused by https://github.com/brave/browser-laptop/pull/14751
